name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Get version
      id: version
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION=${GITHUB_REF#refs/tags/v}
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"
    
    - name: Build CLI
      run: make build
        
    - name: Create distribution package
      run: |
        VERSION="${{ steps.version.outputs.VERSION }}"
        ./release.sh $VERSION
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cheers-${{ steps.version.outputs.VERSION }}
        path: dist/
    
    - name: Create Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/cheers-${{ steps.version.outputs.VERSION }}-macos.tar.gz
          dist/checksums.txt
        body: |
          ## Cheers v${{ steps.version.outputs.VERSION }} 🥂
          
          A delightful macOS notification CLI tool.
          
          ### Installation
          
          ```bash
          # Download and install
          curl -L https://github.com/xorvo/cheers/releases/download/v${{ steps.version.outputs.VERSION }}/cheers-${{ steps.version.outputs.VERSION }}-macos.tar.gz | tar -xz
          ./install.sh
          ```
          
          Or manually:
          ```bash
          # Download, extract, and install
          curl -L https://github.com/xorvo/cheers/releases/download/v${{ steps.version.outputs.VERSION }}/cheers-${{ steps.version.outputs.VERSION }}-macos.tar.gz | tar -xz
          cp -R cheers.app ~/.local/opt/ && ln -s ~/.local/opt/cheers.app/Contents/MacOS/cheers ~/.local/bin/cheers
          ```
          
          ### Usage
          
          ```bash
          # Simple notification
          cheers "Hello World"
          
          # With options
          cheers -t "Success" -m "Build complete!" --sound Glass
          ```
          
          ### Checksums
          See `checksums.txt` in release assets
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}