name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    outputs:
      source_sha256: ${{ steps.source_sha.outputs.SHA256 }}
      version: ${{ steps.version.outputs.VERSION }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Get version
      id: version
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION=${GITHUB_REF#refs/tags/v}
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"
    
    - name: Build CLI
      run: make build
        
    - name: Create distribution package
      run: |
        VERSION="${{ steps.version.outputs.VERSION }}"
        ./release.sh $VERSION
    
    - name: Calculate source tarball SHA256
      id: source_sha
      run: |
        # Wait for GitHub to create the source tarball
        VERSION="${{ steps.version.outputs.VERSION }}"
        SOURCE_URL="https://github.com/xorvo/cheers/archive/refs/tags/v${VERSION}.tar.gz"
        
        # Try to get the SHA256 of the source tarball
        if curl -fsSL "$SOURCE_URL" > /dev/null 2>&1; then
          SHA256=$(curl -fsSL "$SOURCE_URL" | shasum -a 256 | cut -d' ' -f1)
        else
          # If tag doesn't exist yet, calculate from local archive
          git archive --format=tar.gz --prefix=cheers-${VERSION}/ HEAD > source.tar.gz
          SHA256=$(shasum -a 256 source.tar.gz | cut -d' ' -f1)
        fi
        echo "SHA256=$SHA256" >> $GITHUB_OUTPUT
        echo "Source SHA256: $SHA256"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cheers-${{ steps.version.outputs.VERSION }}
        path: dist/
    
    - name: Create Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/cheers-${{ steps.version.outputs.VERSION }}-macos.tar.gz
          dist/checksums.txt
        body: |
          ## Cheers v${{ steps.version.outputs.VERSION }} 🥂
          
          A delightful macOS notification CLI tool.
          
          ### Installation
          
          ```bash
          # Download and install
          curl -L https://github.com/xorvo/cheers/releases/download/v${{ steps.version.outputs.VERSION }}/cheers-${{ steps.version.outputs.VERSION }}-macos.tar.gz | tar -xz
          ./install.sh
          ```
          
          Or manually:
          ```bash
          # Download, extract, and install
          curl -L https://github.com/xorvo/cheers/releases/download/v${{ steps.version.outputs.VERSION }}/cheers-${{ steps.version.outputs.VERSION }}-macos.tar.gz | tar -xz
          cp -R cheers.app ~/.local/opt/ && ln -s ~/.local/opt/cheers.app/Contents/MacOS/cheers ~/.local/bin/cheers
          ```
          
          ### Usage
          
          ```bash
          # Simple notification
          cheers "Hello World"
          
          # With options
          cheers -t "Success" -m "Build complete!" --sound Glass
          ```
          
          ### Checksums
          See `checksums.txt` in release assets
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  update-homebrew-tap:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Trigger Homebrew tap update
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.TAP_UPDATE_TOKEN }}
        repository: xorvo/homebrew-tap
        event-type: update-formula
        client-payload: '{"formula": "cheers", "version": "${{ needs.build.outputs.version }}", "sha256": "${{ needs.build.outputs.source_sha256 }}"}'