name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Get version
      id: version
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION=${GITHUB_REF#refs/tags/v}
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"
    
    - name: Build CLI
      run: make build
        
    - name: Create distribution package
      run: |
        VERSION="${{ steps.version.outputs.VERSION }}"
        ./release.sh $VERSION
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: notifier-${{ steps.version.outputs.VERSION }}
        path: dist/
    
    - name: Create Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/notifier-${{ steps.version.outputs.VERSION }}-macos.tar.gz
          dist/checksums.txt
        body: |
          ## Notifier v${{ steps.version.outputs.VERSION }}
          
          A simple, lightweight macOS notification CLI tool.
          
          ### Installation
          
          ```bash
          # Download and install
          curl -L https://github.com/xorvo/notifier/releases/download/v${{ steps.version.outputs.VERSION }}/notifier-${{ steps.version.outputs.VERSION }}-macos.tar.gz | tar -xz
          ./install.sh
          ```
          
          Or manually:
          ```bash
          # Download, extract, and copy to /usr/local/bin
          curl -L https://github.com/xorvo/notifier/releases/download/v${{ steps.version.outputs.VERSION }}/notifier-${{ steps.version.outputs.VERSION }}-macos.tar.gz | tar -xz
          cp notifier /usr/local/bin/
          ```
          
          ### Usage
          
          ```bash
          # Simple notification
          notifier "Hello World"
          
          # With options
          notifier -t "Title" -m "Message" --sound Glass
          ```
          
          ### Checksums
          See `checksums.txt` in release assets
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}